DELIMITER &
CREATE FUNCTION FN_SEATCHECK(SEATNUM INT)RETURNS INT
BEGIN
DECLARE FLAG INT;
DECLARE SEATAVAILABILITY VARCHAR(30);
SELECT STATUS INTO SEATAVAILABILITY FROM SEATS WHERE SEAT_NO=SEATNUM;

/*check the availability of seats*/
IF SEATAVAILABILITY='AVAILABLE' 
	THEN
		UPDATE SEATS SET STATUS='UNAVAILABLE' WHERE SEAT_NO=SEATNUM;		

		SET FLAG=1;
	ELSE
		SET FLAG=0;
END IF;
RETURN FLAG;
END &
DELIMITER ;


SELECT FN_SEATCHECK(1)
DROP FUNCTION FN_SEATCHECK