DELIMITER &
CREATE PROCEDURE PR_CANCEL_ITEM(IN SEATNUM INT,IN OID INT,OUT MESSAGE VARCHAR(100))
BEGIN

/*check if order id exists*/
IF OID IN(SELECT ID FROM ORDERS)
THEN

/*chck if the order id in transaction table*/
	IF OID NOT IN (SELECT ORDER_ID FROM ORDER_RECORDS)
	THEN
		SET MESSAGE='YOUR ORDER IS BEEN CANCELLED';
		UPDATE ORDERS SET STATUS='CANCELLED';
	ELSE
		SET MESSAGE='SORRY! YOUR ORDER CANNOT BE CANCELLED';
	END IF;
ELSE
SET MESSAGE='THIS ORDER_ID DOES NOT EXISTS';
END IF;
END &
DELIMITER ;

CALL PR_CANCEL_ITEM(1,33,@MESSAGE);
SELECT @MESSAGE;

