DELIMITER &
CREATE FUNCTION SEATCHECK1(SEATNUM INT)RETURNS INT
BEGIN
DECLARE FLAG INT;
DECLARE SEATAVAILABILITY VARCHAR(30);
SELECT SEAT_STATUS INTO SEATAVAILABILITY FROM SEAT WHERE SEAT_NO=SEATNUM;
IF SEATAVAILABILITY='AVAILABLE'
THEN SET FLAG=1;
ELSE
SET FLAG=0;
END IF;
RETURN FLAG;
END &
DELIMITER ;


SELECT SEATCHECK(1)
DROP FUNCTION SEATCHECK1