DELIMITER &
CREATE PROCEDURE CANCEL(IN SEATNUM INT,IN BILLNUM INT)
BEGIN
IF BILLNUM IN(SELECT ID FROM BILLING WHERE SEAT_NUMBER=SEATNUM)
THEN
SELECT 'CANCELLED';
UPDATE BILLING SET STATUS='CANCELLED' WHERE ID=BILLNUM;
UPDATE ORDER_RECORDS SET STATUS='CANCELLED' WHERE ORDER_ID=BILLNUM;
ELSE
SELECT'BILL NUMBER DOES NOT EXIST';
END IF;
END &
DELIMITER ;

CALL CANCEL(1,1)