DELIMITER &
CREATE PROCEDURE PR_CANCEL_ITEM(IN SEATNUM INT,OUT MESSAGE VARCHAR(100))
BEGIN

IF (SELECT STATUS FROM ORDERS WHERE SEAT_NUM=SEATNUM)='REQUESTED'
	THEN
		SET MESSAGE='YOUR ORDER IS BEEN CANCELLED';
		UPDATE ORDERS SET STATUS='CANCELLED' WHERE SEAT_NUM=SEATNUM AND STATUS='REQUESTED';
	ELSE
		SET MESSAGE='SORRY! YOUR ORDER CANNOT BE CANCELLED';
	END IF;
END &
DELIMITER ;

CALL PR_CANCEL_ITEM(2,@MESSAGE);
SELECT @MESSAGE;

DROP PROCEDURE PR_CANCEL_ITEM