DELIMITER &
CREATE PROCEDURE PR_CANCEL_ITEM(IN SEATNUM INT,OUT MESSAGE VARCHAR(100))
BEGIN
IF(SELECT SEAT_NUM FROM ORDERS WHERE SEAT_NUM=SEATNUM)
THEN
	IF(SELECT ID FROM ORDERS WHERE SEAT_NUM=SEATNUM AND STATUS='REQUESTED')IS NOT NULL
	THEN 
		SET MESSAGE='YOUR ORDER IS BEEN CANCELLED';
		UPDATE ORDERS SET STATUS='CANCELLED' WHERE SEAT_NUM=SEATNUM AND STATUS='REQUESTED';
	ELSE
		SET MESSAGE='SORRY! YOUR ORDER CANNOT BE CANCELLED';
	END IF;
ELSE
SET MESSAGE='SORRY! PLEASE CHECK THE SEAT NUMBER YOU HAVE GIVEN!';
END IF;
END &
DELIMITER ;

CALL PR_CANCEL_ITEM(1,@MESSAGE);
SELECT @MESSAGE;

DROP PROCEDURE PR_CANCEL_ITEM