DELIMITER &
CREATE FUNCTION ITEM_EXISTS(ITEMS VARCHAR(30))
RETURNS INT
BEGIN
DECLARE FLAG INT;
IF EXISTS(SELECT ITEM FROM MENU_ITEMS WHERE ITEM=ITEMS)
THEN
SET FLAG=1;
ELSE
SET FLAG=0;
END IF;
RETURN FLAG;
END &
DELIMITER ;

DROP FUNCTION ITEM_EXISTS
SELECT ITEM_EXISTS('NAA')