DELIMITER &
CREATE FUNCTION FN_SEATCHECK(SEATNUM INT)RETURNS INT
BEGIN
DECLARE FLAG INT;
DECLARE SEATAVAILABILITY BOOLEAN;
SELECT CONCURRENT_USER_STATE INTO SEATAVAILABILITY FROM SEATS WHERE SEAT_NO=SEATNUM;

/*check the availability of seats*/
IF SEATAVAILABILITY=0
	THEN

		SET FLAG=1;
	ELSE
		SET FLAG=0;
END IF;
RETURN FLAG;
END &
DELIMITER ;


SELECT FN_SEATCHECK(1)
DROP FUNCTION FN_SEATCHECK