DELIMITER &
CREATE PROCEDURE MENU(SESSION_NAME VARCHAR(20))
BEGIN
DECLARE SESSION_ID INT;
SELECT ID INTO SESSION_ID FROM FOOD_TYPES WHERE TYPE_NAME=SESSION_NAME;
SELECT ITEM,RATE FROM MENU_ITEMS JOIN ITEM_SCHEDULES ON MENU_ITEMS.`ID`=ITEM_SCHEDULES.`MENU_ID` AND ITEM_SCHEDULES.`FOOD_ID`=SESSION_ID;
END &
DELIMITER ;

CALL MENU('Dinner')
DROP PROCEDURE MENU;