DELIMITER &
CREATE PROCEDURE PR_SEATCHECK(IN SEATNUM INT,OUT SEAT_MSG VARCHAR(20))
BEGIN
DECLARE FLAG INT;
DECLARE SEATAVAILABILITY VARCHAR(30);
DECLARE TOGGLE_SEATS BOOLEAN;
SELECT CONCURRENT_USER_STATE INTO TOGGLE_SEATS FROM SEATS WHERE SEAT_NO=SEATNUM; 
SELECT STATUS INTO SEATAVAILABILITY FROM SEATS WHERE SEAT_NO=SEATNUM;

/*check the availability of seats*/
IF SEATAVAILABILITY='AVAILABLE' 
THEN
	IF TOGGLE_SEATS=FALSE
	THEN
		UPDATE SEATS SET CONCURRENT_USER_STATE=TRUE WHERE SEAT_NO=SEATNUM;
		SET FLAG=1;
		SELECT FLAG INTO SEAT_MSG;
	ELSE
		SET FLAG=0;
		SELECT FLAG INTO SEAT_MSG;


	END IF;
	ELSE
		SET FLAG=0;
		SELECT FLAG INTO SEAT_MSG;

END IF;
END &
DELIMITER ;


CALL PR_SEATCHECK(1,@FLAG,@SEAT_MSG)
DROP PROCEDURE PR_SEATCHECK