DELIMITER &
CREATE PROCEDURE CHECKITEM(IN ITEM1 VARCHAR(20),IN QUANTS INT,IN SEATNOS INT)
BEGIN
DECLARE MENUID INT;
DECLARE FID INT DEFAULT 0;
IF ITEM1 IN(SELECT ITEMS FROM MENU_ITEM)
THEN
IF (SELECT COUNT(DISTINCT(ITEM))FROM ORDER_GIVEN)<=5
THEN
INSERT INTO ORDER_GIVEN(ITEM,QUANTITY)VALUES(ITEM1,QUANTS);
SELECT Id INTO MENUID FROM MENU_ITEM WHERE ITEMS=ITEM1;
SELECT DISTINCT(SCHEDULES.`FOOD_TYPE`)INTO FID FROM SCHEDULES INNER JOIN TYPE_OF_FOOD WHERE SCHEDULES.`MENU_TYPE`=MENUID
AND SCHEDULES.`FOOD_TYPE` IN(SELECT TYPE_OF_FOOD.`ID` FROM TYPE_OF_FOOD WHERE CURTIME()>=TYPE_OF_FOOD.`TIME_DURATION_FROM` AND CURTIME()<=TYPE_OF_FOOD.`TIMEDURATIONTO`);
IF FID=0
THEN
SELECT'This item is not available at this time';
ELSE
CALL REMAINING(ITEM1,QUANTS,SEATNOS,FID); 
END IF;
ELSE 
SELECT 'sorry! you can order only 5 items';
END IF;
ELSE
SELECT ITEM1,'unavailable';
END IF;
END &
DELIMITER ;

DROP PROCEDURE CHECKITEM
CALL CHECKITEM('South Indian Meals',2,1)
