
DELIMITER &
CREATE PROCEDURE REMAINING(IN ITEM VARCHAR(20),IN QUANTS INT,IN SEAT INT,IN FOODID INT)
BEGIN
DECLARE AMOUNT INT;
DECLARE COUNTS INT;
DECLARE REM INT;
DECLARE MENUID INT;
DECLARE CHARGE INT;
DECLARE TOT INT;
DECLARE BILLNO INT;
SELECT ID INTO MENUID FROM MENU_ITEM WHERE ITEMS=ITEM;
IF ITEM IN(SELECT FOOD_ORDERED FROM ORDER_RECORDS WHERE ORDER_DATE=CURDATE())
		THEN
		SELECT SUM(QUANTITY) INTO COUNTS FROM ORDER_RECORDS WHERE FOOD_ORDERED=ITEM AND STATUS='ORDER DISPATCHED';
		SELECT QUANTITY INTO AMOUNT FROM SCHEDULES WHERE MENU_TYPE=MENUID AND FOOD_TYPE=FOODID;
		SET REM=AMOUNT-COUNTS;
		ELSE
		SELECT QUANTITY INTO AMOUNT FROM SCHEDULES WHERE MENU_TYPE=MENUID AND FOOD_TYPE=FOODID;
		SET REM=AMOUNT;
		END IF;
		IF QUANTS<=0
		THEN
		SELECT'PLEASE GIVE A VALID QUANTITY!';
		ELSE
		IF QUANTS>REM
		THEN
		SELECT'SORRY!THE QUANTITY YOU HAVE ASKED IS CURRENTLY OUT OF STOCK.PLEASE TRY SOMETHING ELSE!',REM AS REMAINING,'QUANTITY IS AVAILABLE' AS COMMENTS;
		ELSE
		SELECT'ORDER PLACED';
		SELECT DISTINCT(RATE)INTO CHARGE  FROM MENU_ITEM WHERE ITEMS=ITEM;
		SET TOT=QUANTS*CHARGE;
		SELECT ID INTO BILLNO FROM BILLING WHERE STATUS='YET TO BE PAID' AND SEAT_NUMBER=SEAT;
		INSERT INTO ORDER_RECORDS(ORDER_ID,SEAT_NUMBER,FOOD_ORDERED,QUANTITY,TOTAL,ORDER_DATE,STATUS) VALUES(BILLNO,SEAT,ITEM,QUANTS,TOT,NOW(),'ORDER DISPATCHED');
		END IF;
		END IF;
END &
DELIMITER;

CALL REMAINING('COFFEE',1,1,1)
DROP PROCEDURE REMAINING


