
DELIMITER &
CREATE PROCEDURE PR_VALIDATION_ENTRY(IN MENU_ITEM VARCHAR(20),IN QUANTS INT,IN SEAT INT,IN FOODID INT,IN O_ID INT,OUT RESULT VARCHAR(100) )
BEGIN
DECLARE AMOUNT INT;
DECLARE COUNTS INT;
DECLARE REM INT;
DECLARE MENUID INT;
DECLARE CHARGE INT;
DECLARE TOTAL INT;
SELECT ID INTO MENUID FROM MENU_ITEMS WHERE ITEM=MENU_ITEM;

/*check if the item is in the menulist*/
IF MENU_ITEM IN(SELECT MENU_ID FROM ORDER_RECORDS WHERE ORDER_DATE=CURDATE())
THEN
	SELECT SUM(QUANTITY) INTO COUNTS FROM ORDER_RECORDS WHERE MENU_ID=MENU_ITEM AND ORDER_TRACK='ORDER DISPATCHED';
	SELECT QUANTITY INTO AMOUNT FROM ITEM_SCHEDULES WHERE ITEM_SCHEDULES.`MENU_ID`=MENUID AND ITEM_SCHEDULES.`FOOD_ID`=FOODID;
	SET REM=AMOUNT-COUNTS;
ELSE
	SELECT QUANTITY INTO AMOUNT FROM ITEM_SCHEDULES WHERE ITEM_SCHEDULES.`MENU_ID`=MENUID AND ITEM_SCHEDULES.`FOOD_ID`=FOODID;
	SET REM=AMOUNT;
END IF;

/*if the quantity is 0*/
IF QUANTS<=0
THEN
	SET RESULT='PLEASE GIVE A VALID QUANTITY!';
ELSE

	/*check if the remaining is less than ordered*/
	IF QUANTS>REM
	THEN
		SET RESULT='SORRY!THE QUANTITY YOU HAVE ASKED IS CURRENTLY OUT OF STOCK.PLEASE TRY SOMETHING ELSE!' ;
	ELSE
		SET RESULT='ORDER PLACED';
		SELECT DISTINCT(RATE)INTO CHARGE  FROM MENU_ITEMS WHERE ITEM=MENU_ITEM;
		SET TOTAL=QUANTS*CHARGE;
		INSERT INTO ORDER_RECORDS(ORDER_ID,SEAT_NUMBER,MENU_ID,QUANTITY,TOTAL_PRICE,ORDER_DATE,ORDER_TRACK) VALUES(O_ID,SEAT,MENUID,QUANTS,TOTAL,NOW(),'ORDER DISPATCHED');
	END IF;
END IF;
END &
DELIMITER;

CALL PR_VALIDATION_ENTRY('Coffee',20,1,1,1,@RESULT);
SELECT @RESULT;



